### ISSUE TITLE
Alignment for NSString *shorthandWelcome seems like it's messed up

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/reading-ios-using-methods#5]
Not sure, but the content int he code block for NSString *shorthandWelcome is difficult to read and may be mis-aligned.

**Comment by markedwardmurray** [comment]
Learn doesn't render the markdown well but the example displays correctly in Github. The spacing is the point of these examples so the purpose of the section is lost because of this.

@kvignali 

https://learn.co/admin/lessons/7321

**Comment by kvignali** [comment]
I've opened a big picture issue regarding Learn rendering markdown differently than Github on the Ironboard repo.

**Comment by markedwardmurray** [comment]
Closing this as an issue on the repo, since it's a broader problem.

**Comment by AnnJohn** [comment]
Closing issue. Handed over to engineering.
